import Brands from '@/components/Brands/Brands';
import Carousel from '@/components/Carousel/Carousel';
import CatalogList from '@/components/CatalogList/CatalogList';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';

/**
 * Catalog page.
 * @typedef {Object} Props
 * @property {any} list
 * @param {Props} props
 * @returns {JSX.Element}
 */
const Catalog = ({ list }) => {
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      signIn();
    },
  });

  if (status === 'loading') {
    return 'Loading or not authenticated...';
  }

  return (
    <>
      <Head>
        <title>Disney+ España | Películas y series</title>
      </Head>
      <Carousel />
      <Brands />
      <CatalogList list={list} />
    </>
  );
};

export async function getStaticProps() {
  // const categories = [
  //   {
  //     title: 'Películas más valoradas',
  //     url: `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.TMBD_API_KEY}&language=en-US&page=1`,
  //   },
  //   {
  //     title: 'Películas populares',
  //     url: `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.TMBD_API_KEY}&language=en-US&page=1`,
  //   },
  //   {
  //     title: 'Series más valoradas',
  //     url: `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.TMBD_API_KEY}&language=en-US&page=1`,
  //   },
  //   {
  //     title: 'Series populares',
  //     url: `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.TMBD_API_KEY}&language=en-US&page=1`,
  //   },
  // ];

  // const fetchedData = await Promise.allSettled(
  //   categories.map((category) => fetch(category.url))
  // );
  // const data = await Promise.all(
  //   fetchedData.map((fetched) => fetched.value.json())
  // );

  // const list = data.map((category, index) => ({
  //   ...category,
  //   title: categories[index].title,
  // }));

  const list = [
    {
      title: 'Películas más valoradas',
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
          genre_ids: [18, 80],
          id: 238,
          original_language: 'en',
          original_title: 'The Godfather',
          overview:
            'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
          popularity: 106.178,
          poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
          release_date: '1972-03-14',
          title: 'The Godfather',
          video: false,
          vote_average: 8.7,
          vote_count: 16528,
        },
        {
          adult: false,
          backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
          genre_ids: [18, 80],
          id: 278,
          original_language: 'en',
          original_title: 'The Shawshank Redemption',
          overview:
            'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
          popularity: 88.571,
          poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
          release_date: '1994-09-23',
          title: 'The Shawshank Redemption',
          video: false,
          vote_average: 8.7,
          vote_count: 22213,
        },
        {
          adult: false,
          backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
          genre_ids: [18, 80],
          id: 240,
          original_language: 'en',
          original_title: 'The Godfather Part II',
          overview:
            'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
          popularity: 61.506,
          poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
          release_date: '1974-12-20',
          title: 'The Godfather Part II',
          video: false,
          vote_average: 8.6,
          vote_count: 9998,
        },
        {
          adult: false,
          backdrop_path: '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
          genre_ids: [35, 18, 10749],
          id: 19404,
          original_language: 'hi',
          original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
          overview:
            'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
          popularity: 37.362,
          poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
          release_date: '1995-10-19',
          title: 'Dilwale Dulhania Le Jayenge',
          video: false,
          vote_average: 8.6,
          vote_count: 3853,
        },
        {
          adult: false,
          backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
          genre_ids: [18, 36, 10752],
          id: 424,
          original_language: 'en',
          original_title: "Schindler's List",
          overview:
            'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
          popularity: 81.556,
          poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          release_date: '1993-12-15',
          title: "Schindler's List",
          video: false,
          vote_average: 8.6,
          vote_count: 13177,
        },
        {
          adult: false,
          backdrop_path: '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
          genre_ids: [10751, 18],
          id: 667257,
          original_language: 'es',
          original_title: 'Cosas imposibles',
          overview:
            'Matilde is a woman who, after the death of her husband - a man who constantly abused her - finds her new best friend in Miguel, her young, insecure, disoriented and even dealer neighbor',
          popularity: 11.23,
          poster_path: '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
          release_date: '2021-06-17',
          title: 'Impossible Things',
          video: false,
          vote_average: 8.5,
          vote_count: 266,
        },
        {
          adult: false,
          backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
          genre_ids: [16, 10751, 14],
          id: 129,
          original_language: 'ja',
          original_title: '千と千尋の神隠し',
          overview:
            'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
          popularity: 87.647,
          poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          release_date: '2001-07-20',
          title: 'Spirited Away',
          video: false,
          vote_average: 8.5,
          vote_count: 13304,
        },
        {
          adult: false,
          backdrop_path: '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
          genre_ids: [10749, 16],
          id: 372754,
          original_language: 'ja',
          original_title: '同級生',
          overview:
            'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
          popularity: 14.383,
          poster_path: '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
          release_date: '2016-02-20',
          title: 'Dou kyu sei – Classmates',
          video: false,
          vote_average: 8.5,
          vote_count: 253,
        },
        {
          adult: false,
          backdrop_path: '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
          genre_ids: [10749, 16, 18],
          id: 372058,
          original_language: 'ja',
          original_title: '君の名は。',
          overview:
            'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
          popularity: 134.648,
          poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
          release_date: '2016-08-26',
          title: 'Your Name.',
          video: false,
          vote_average: 8.5,
          vote_count: 9032,
        },
        {
          adult: false,
          backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
          genre_ids: [18],
          id: 389,
          original_language: 'en',
          original_title: '12 Angry Men',
          overview:
            "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
          popularity: 30.168,
          poster_path: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
          release_date: '1957-04-10',
          title: '12 Angry Men',
          video: false,
          vote_average: 8.5,
          vote_count: 6640,
        },
        {
          adult: false,
          backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
          genre_ids: [35, 53, 18],
          id: 496243,
          original_language: 'ko',
          original_title: '기생충',
          overview:
            "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
          popularity: 58.051,
          poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
          release_date: '2019-05-30',
          title: 'Parasite',
          video: false,
          vote_average: 8.5,
          vote_count: 14338,
        },
        {
          adult: false,
          backdrop_path: '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
          genre_ids: [10749],
          id: 724089,
          original_language: 'en',
          original_title: "Gabriel's Inferno: Part II",
          overview:
            "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
          popularity: 12.333,
          poster_path: '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
          release_date: '2020-07-31',
          title: "Gabriel's Inferno: Part II",
          video: false,
          vote_average: 8.5,
          vote_count: 1433,
        },
        {
          adult: false,
          backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
          genre_ids: [10749],
          id: 696374,
          original_language: 'en',
          original_title: "Gabriel's Inferno",
          overview:
            "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
          popularity: 11.587,
          poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
          release_date: '2020-05-29',
          title: "Gabriel's Inferno",
          video: false,
          vote_average: 8.5,
          vote_count: 2280,
        },
        {
          adult: false,
          backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
          genre_ids: [14, 18, 80],
          id: 497,
          original_language: 'en',
          original_title: 'The Green Mile',
          overview:
            "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
          popularity: 74.228,
          poster_path: '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
          release_date: '1999-12-10',
          title: 'The Green Mile',
          video: false,
          vote_average: 8.5,
          vote_count: 14354,
        },
        {
          adult: false,
          backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
          genre_ids: [18, 28, 80, 53],
          id: 155,
          original_language: 'en',
          original_title: 'The Dark Knight',
          overview:
            'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
          popularity: 74.053,
          poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
          release_date: '2008-07-14',
          title: 'The Dark Knight',
          video: false,
          vote_average: 8.5,
          vote_count: 28197,
        },
        {
          adult: false,
          backdrop_path: '/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg',
          genre_ids: [10749, 18],
          id: 730154,
          original_language: 'ja',
          original_title: 'きみの瞳が問いかけている',
          overview:
            "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
          popularity: 40.973,
          poster_path: '/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg',
          release_date: '2020-10-23',
          title: 'Your Eyes Tell',
          video: false,
          vote_average: 8.5,
          vote_count: 349,
        },
        {
          adult: false,
          backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
          genre_ids: [53, 80],
          id: 680,
          original_language: 'en',
          original_title: 'Pulp Fiction',
          overview:
            "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
          popularity: 53.693,
          poster_path: '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
          release_date: '1994-09-10',
          title: 'Pulp Fiction',
          video: false,
          vote_average: 8.5,
          vote_count: 23718,
        },
        {
          adult: false,
          backdrop_path: '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
          genre_ids: [37],
          id: 429,
          original_language: 'it',
          original_title: 'Il buono, il brutto, il cattivo',
          overview:
            'While the Civil War rages on, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
          popularity: 39.441,
          poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
          release_date: '1966-12-23',
          title: 'The Good, the Bad and the Ugly',
          video: false,
          vote_average: 8.5,
          vote_count: 6844,
        },
        {
          adult: false,
          backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
          genre_ids: [12, 14, 28],
          id: 122,
          original_language: 'en',
          original_title: 'The Lord of the Rings: The Return of the King',
          overview:
            "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
          popularity: 192.728,
          poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
          release_date: '2003-12-01',
          title: 'The Lord of the Rings: The Return of the King',
          video: false,
          vote_average: 8.5,
          vote_count: 20120,
        },
        {
          adult: false,
          backdrop_path: '/oJmBWLUCKbgra8D9ZrLE1nBic5v.jpg',
          genre_ids: [35, 18, 10749],
          id: 13,
          original_language: 'en',
          original_title: 'Forrest Gump',
          overview:
            'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
          popularity: 58.935,
          poster_path: '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
          release_date: '1994-06-23',
          title: 'Forrest Gump',
          video: false,
          vote_average: 8.5,
          vote_count: 23252,
        },
      ],
      total_pages: 515,
      total_results: 10281,
      title: 'Películas más valoradas',
    },
    {
      title: 'Películas populares',
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg',
          genre_ids: [16, 878, 28],
          id: 610150,
          original_language: 'ja',
          original_title: 'ドラゴンボール超 スーパーヒーロー',
          overview:
            'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',
          popularity: 8753.85,
          poster_path: '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg',
          release_date: '2022-06-11',
          title: 'Dragon Ball Super: Super Hero',
          video: false,
          vote_average: 8,
          vote_count: 1294,
        },
        {
          adult: false,
          backdrop_path: '/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg',
          genre_ids: [28, 18, 878],
          id: 629176,
          original_language: 'en',
          original_title: 'Samaritan',
          overview:
            'Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.',
          popularity: 5115.365,
          poster_path: '/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg',
          release_date: '2022-08-25',
          title: 'Samaritan',
          video: false,
          vote_average: 7,
          vote_count: 813,
        },
        {
          adult: false,
          backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
          genre_ids: [28, 12, 14],
          id: 616037,
          original_language: 'en',
          original_title: 'Thor: Love and Thunder',
          overview:
            'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
          popularity: 4237.659,
          poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
          release_date: '2022-07-06',
          title: 'Thor: Love and Thunder',
          video: false,
          vote_average: 6.8,
          vote_count: 2326,
        },
        {
          adult: false,
          backdrop_path: '/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg',
          genre_ids: [28, 12, 14],
          id: 960700,
          original_language: 'ja',
          original_title: '鋼の錬金術師 完結編 復讐者スカー',
          overview:
            'The Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.',
          popularity: 3105.174,
          poster_path: '/14lQfkLDgEIrEtyUMfj5rJEKVlS.jpg',
          release_date: '2022-05-20',
          title: 'Fullmetal Alchemist the Revenge of Scar',
          video: false,
          vote_average: 6.7,
          vote_count: 53,
        },
        {
          adult: false,
          backdrop_path: '/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg',
          genre_ids: [53, 28],
          id: 766507,
          original_language: 'en',
          original_title: 'Prey',
          overview:
            'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
          popularity: 2818.224,
          poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
          release_date: '2022-08-02',
          title: 'Prey',
          video: false,
          vote_average: 8,
          vote_count: 3646,
        },
        {
          adult: false,
          backdrop_path: '/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg',
          genre_ids: [16, 28, 10751, 878, 35],
          id: 539681,
          original_language: 'en',
          original_title: 'DC League of Super-Pets',
          overview:
            'When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.',
          popularity: 2738.291,
          poster_path: '/r7XifzvtezNt31ypvsmb6Oqxw49.jpg',
          release_date: '2022-07-27',
          title: 'DC League of Super-Pets',
          video: false,
          vote_average: 7.6,
          vote_count: 434,
        },
        {
          adult: false,
          backdrop_path: '/rHzoz94bRfyfNLjiIB26Wt5KDHE.jpg',
          genre_ids: [28, 80, 35, 12],
          id: 773867,
          original_language: 'ko',
          original_title: '서울대작전',
          overview:
            'Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.',
          popularity: 2462.344,
          poster_path: '/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg',
          release_date: '2022-08-26',
          title: 'Seoul Vibe',
          video: false,
          vote_average: 7,
          vote_count: 48,
        },
        {
          adult: false,
          backdrop_path: '/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg',
          genre_ids: [53],
          id: 985939,
          original_language: 'en',
          original_title: 'Fall',
          overview:
            'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.',
          popularity: 2453.108,
          poster_path: '/v28T5F1IygM8vXWZIycfNEm3xcL.jpg',
          release_date: '2022-08-11',
          title: 'Fall',
          video: false,
          vote_average: 7.4,
          vote_count: 192,
        },
        {
          adult: false,
          backdrop_path: '/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg',
          genre_ids: [27, 9648, 878, 53],
          id: 762504,
          original_language: 'en',
          original_title: 'Nope',
          overview:
            'Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.',
          popularity: 2087.208,
          poster_path: '/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg',
          release_date: '2022-07-20',
          title: 'Nope',
          video: false,
          vote_average: 7.1,
          vote_count: 1253,
        },
        {
          adult: false,
          backdrop_path: '/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg',
          genre_ids: [12, 28, 878],
          id: 507086,
          original_language: 'en',
          original_title: 'Jurassic World Dominion',
          overview:
            'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.',
          popularity: 2083.754,
          poster_path: '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg',
          release_date: '2022-06-01',
          title: 'Jurassic World Dominion',
          video: false,
          vote_average: 7.1,
          vote_count: 3216,
        },
        {
          adult: false,
          backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
          genre_ids: [28, 18],
          id: 361743,
          original_language: 'en',
          original_title: 'Top Gun: Maverick',
          overview:
            'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
          popularity: 2029.875,
          poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
          release_date: '2022-05-24',
          title: 'Top Gun: Maverick',
          video: false,
          vote_average: 8.4,
          vote_count: 3504,
        },
        {
          adult: false,
          backdrop_path: '/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg',
          genre_ids: [28, 18],
          id: 579974,
          original_language: 'te',
          original_title: 'రౌద్రం రణం రుధిరం',
          overview:
            "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
          popularity: 1783.869,
          poster_path: '/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg',
          release_date: '2022-03-24',
          title: 'RRR',
          video: false,
          vote_average: 7.8,
          vote_count: 306,
        },
        {
          adult: false,
          backdrop_path: '/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg',
          genre_ids: [16, 12, 35, 14],
          id: 438148,
          original_language: 'en',
          original_title: 'Minions: The Rise of Gru',
          overview:
            'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.',
          popularity: 1769.796,
          poster_path: '/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg',
          release_date: '2022-06-29',
          title: 'Minions: The Rise of Gru',
          video: false,
          vote_average: 7.7,
          vote_count: 1847,
        },
        {
          adult: false,
          backdrop_path: '/pkLegAR3G5T63B2Xz2ijbD1BAm8.jpg',
          genre_ids: [53, 27, 28],
          id: 927341,
          original_language: 'en',
          original_title: 'Hunting Ava Bravo',
          overview:
            'Billionaire sportsman Buddy King unwinds by hunting human captives on his remote mountain estate. But his latest victim, Ava Bravo, is no easy target.',
          popularity: 1714.811,
          poster_path: '/etc6HKBEhNySNnYU2nRgbSeIyoW.jpg',
          release_date: '2022-04-01',
          title: 'Hunting Ava Bravo',
          video: false,
          vote_average: 6.4,
          vote_count: 42,
        },
        {
          adult: false,
          backdrop_path: '/eiBMu2noc6r1QZLfQlFhfVtbXeM.jpg',
          genre_ids: [28, 53, 9648],
          id: 997120,
          original_language: 'en',
          original_title: 'Sniper: Rogue Mission',
          overview:
            'When a crooked federal agent is involved in a human sex trafficking ring, Sniper and CIA Rookie Brandon Beckett goes rogue, teaming up with his former allies Homeland Security Agent Zero and assassin Lady Death to uncover the corrupt agent and take down the criminal organization.',
          popularity: 1635.838,
          poster_path: '/jSL5TqroJsDAIgBdELBwby1uhf1.jpg',
          release_date: '2022-08-15',
          title: 'Sniper: Rogue Mission',
          video: false,
          vote_average: 6.8,
          vote_count: 50,
        },
        {
          adult: false,
          backdrop_path: '/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg',
          genre_ids: [10749, 18],
          id: 744276,
          original_language: 'en',
          original_title: 'After Ever Happy',
          overview:
            "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
          popularity: 1585.309,
          poster_path: '/moogpu8rNkEjTgFyLXwhPghft5w.jpg',
          release_date: '2022-08-24',
          title: 'After Ever Happy',
          video: false,
          vote_average: 6.5,
          vote_count: 45,
        },
        {
          adult: false,
          backdrop_path: '/zlLQXKsSa2CEkz3UBFWPUPX90PN.jpg',
          genre_ids: [53],
          id: 968857,
          original_language: 'en',
          original_title: 'Looks Can Kill',
          overview:
            'A group of models is killed off, one by one, and everyone is a suspect.',
          popularity: 1486.748,
          poster_path: '/1uy2PNFwtkqH3mhGd6irk5aeIrF.jpg',
          release_date: '2022-02-01',
          title: 'Looks Can Kill',
          video: false,
          vote_average: 5.7,
          vote_count: 5,
        },
        {
          adult: false,
          backdrop_path: '/mCAkUizRRIwKMOlne9CIoJ3utSc.jpg',
          genre_ids: [53, 10770, 28],
          id: 951368,
          original_language: 'en',
          original_title: 'Your Boyfriend Is Mine',
          overview:
            'Over the objection of his girlfriend, Ben agrees to take a job as the “live in” man servant to a wealthy businesswoman, Amanda, but quickly realizes he has made a deal with the devil, and has put himself and his girlfriend in mortal jeopardy',
          popularity: 1413.258,
          poster_path: '/2OOYNZLKjdX8Z5KNyz7zZnHmodJ.jpg',
          release_date: '2022-03-19',
          title: 'Your Boyfriend Is Mine',
          video: false,
          vote_average: 6.2,
          vote_count: 11,
        },
        {
          adult: false,
          backdrop_path: '/5L6RPHHUFlsliTqKRmUxFnIkXpR.jpg',
          genre_ids: [28, 14, 27, 35],
          id: 755566,
          original_language: 'en',
          original_title: 'Day Shift',
          overview:
            "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
          popularity: 1403.411,
          poster_path: '/bI7lGR5HuYlENlp11brKUAaPHuO.jpg',
          release_date: '2022-08-10',
          title: 'Day Shift',
          video: false,
          vote_average: 6.9,
          vote_count: 881,
        },
        {
          adult: false,
          backdrop_path: '/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg',
          genre_ids: [27, 53],
          id: 756999,
          original_language: 'en',
          original_title: 'The Black Phone',
          overview:
            'Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.',
          popularity: 1365.863,
          poster_path: '/lr11mCT85T1JanlgjMuhs9nMht4.jpg',
          release_date: '2022-06-22',
          title: 'The Black Phone',
          video: false,
          vote_average: 7.9,
          vote_count: 2374,
        },
      ],
      total_pages: 35035,
      total_results: 700699,
      title: 'Películas populares',
    },
    {
      title: 'Series más valoradas',
      page: 1,
      results: [
        {
          backdrop_path: '/7q448EVOnuE3gVAx24krzO7SNXM.jpg',
          first_air_date: '2021-09-03',
          genre_ids: [10764],
          id: 130392,
          name: "The D'Amelio Show",
          origin_country: ['US'],
          original_language: 'en',
          original_name: "The D'Amelio Show",
          overview:
            'From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.',
          popularity: 35.23,
          poster_path: '/z0iCS5Znx7TeRwlYSd4c01Z0lFx.jpg',
          vote_average: 9.2,
          vote_count: 2874,
        },
        {
          backdrop_path: '/igxqysAqY84xQISHbZllwV67JPr.jpg',
          first_air_date: '1978-04-04',
          genre_ids: [16, 10759, 10751, 10762, 10765],
          id: 19239,
          name: 'Conan, the Boy in Future',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '未来少年コナン',
          overview:
            'After the great disaster of 2008, a war that destroyed the planet, the world is now largely ocean with the continents having sunk. Conan lives on a remote island with his grandpa and nature, never having seen another human being. But one day a mysterious girl, Lana, washes up on his beach. The two become quick friends, but she’s soon kidnapped and taken to Industria, a technological remainder from the world before. Conan leaves his island in pursuit, braving new lands and many hardships with new friends and enemies just beyond the horizon.',
          popularity: 24.993,
          poster_path: '/tmlhwdTBA264iQF2Us5vWdKz1fE.jpg',
          vote_average: 8.9,
          vote_count: 110,
        },
        {
          backdrop_path: '/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
          first_air_date: '2021-11-06',
          genre_ids: [16, 10765, 10759, 18],
          id: 94605,
          name: 'Arcane',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Arcane',
          overview:
            'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
          popularity: 121.991,
          poster_path: '/xQ6GijOFnxTyUzqiwGpVxgfcgqI.jpg',
          vote_average: 8.9,
          vote_count: 2461,
        },
        {
          backdrop_path: '/iLR6tKvMu67oSK0DIgDutkPBaiy.jpg',
          first_air_date: '2018-07-08',
          genre_ids: [35, 16],
          id: 80539,
          name: 'Asobi Asobase - workshop of fun -',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'あそびあそばせ',
          overview:
            'During recess, Olivia, a foreign transfer student who doesn\'t know English, plays a game of "look-the-other-way" with Hanako Honda, a loud-mouthed airhead. Their rowdy behavior spurs the ire of Kasumi Nomura, a deadpan loner constantly teased by her older sister for her tendency to lose games. Not willing to compete, Kasumi declines Olivia\'s offer to join the fun, but eventually gets involved anyway and dispenses her own brand of mischief. Soon, a strange friendship blossoms between the peculiar trio, and they decide to form the "Pastime Club," where they are free to resume their daily hijinks.\n\nWhether it be failing to learn English, trying desperately to become popular, or getting caught by teachers at the wrong time, school life will never be boring when these girls are up to their hilarious antics.',
          popularity: 18.209,
          poster_path: '/zWE3bnCILcRpfQCsxBkMsgcEjOE.jpg',
          vote_average: 8.8,
          vote_count: 109,
        },
        {
          backdrop_path: '/84XPpjGvxNyExjSuLQe0SzioErt.jpg',
          first_air_date: '2008-01-20',
          genre_ids: [18],
          id: 1396,
          name: 'Breaking Bad',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Breaking Bad',
          overview:
            "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
          popularity: 674.586,
          poster_path: '/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
          vote_average: 8.8,
          vote_count: 9670,
        },
        {
          backdrop_path: '/uGy4DCmM33I7l86W7iCskNkvmLD.jpg',
          first_air_date: '2013-12-02',
          genre_ids: [16, 35, 10765, 10759],
          id: 60625,
          name: 'Rick and Morty',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Rick and Morty',
          overview:
            "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
          popularity: 1566.773,
          poster_path: '/sGVCWtLG37mLOhl11qQVrjKsDzx.jpg',
          vote_average: 8.7,
          vote_count: 6839,
        },
        {
          backdrop_path: '/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg',
          first_air_date: '2016-04-03',
          genre_ids: [10759, 16],
          id: 65930,
          name: 'My Hero Academia',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '僕のヒーローアカデミア',
          overview:
            "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
          popularity: 62.735,
          poster_path: '/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg',
          vote_average: 8.7,
          vote_count: 3834,
        },
        {
          backdrop_path: '/5J4f4XDeRg7c7bHcXK26e1gkb0t.jpg',
          first_air_date: '2018-10-04',
          genre_ids: [16, 35, 9648],
          id: 82739,
          name: 'Rascal Does Not Dream of Bunny Girl Senpai',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '青春ブタ野郎はバニーガール先輩の夢を見ない',
          overview:
            "Puberty Syndrome—a rumored, mysterious syndrome that only affects those in their puberty. For example, a bunny girl suddenly appeared in front of Sakuta Azusagawa. The bunny girl's real identity is Mai Sakurajima, a teenage celebrity who is currently an inactive high school senior. For some reason, her charming figure does not reflect in the eyes of others. In the course of revealing the mystery behind this phenomenon, Sakuta begins to explore his feelings towards Mai. Set in a city where the skies and seas shine, Sakuta unfolds the meaning behind his bizarre encounters on women with the said syndrome.",
          popularity: 53.669,
          poster_path: '/cU4jHfo1Q9AEPnFqFqtuSA74gdi.jpg',
          vote_average: 8.7,
          vote_count: 969,
        },
        {
          backdrop_path: '/c8dm74uPCMA27iKAR1WnHKTsI9h.jpg',
          first_air_date: '2015-08-01',
          genre_ids: [10764],
          id: 77696,
          name: 'Run BTS!',
          origin_country: ['KR'],
          original_language: 'ko',
          original_name: '달려라 방탄!',
          overview:
            'Run BTS! is a South Korean show by the boy-group BTS. The show is all about BTS doing activities, challenges and lots more.',
          popularity: 16.064,
          poster_path: '/xxv8Ibs8Anni6qrWkAf60rDsPCu.jpg',
          vote_average: 8.7,
          vote_count: 291,
        },
        {
          backdrop_path: '/smSbK5cd8T9XHcxEUcems23BDEF.jpg',
          first_air_date: '2016-12-02',
          genre_ids: [18, 10765],
          id: 67915,
          name: 'Goblin',
          origin_country: ['KR'],
          original_language: 'ko',
          original_name: '쓸쓸하고 찬란하神-도깨비',
          overview:
            'In his quest for a bride to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper and a sprightly student with a tragic past.',
          popularity: 131.13,
          poster_path: '/c2gon6zbqzL73DOl8mPQMMUJXvE.jpg',
          vote_average: 8.7,
          vote_count: 2260,
        },
        {
          backdrop_path: '/legulSo298h0xPqwQ2y1k9bSzxo.jpg',
          first_air_date: '2020-01-10',
          genre_ids: [16, 9648, 35],
          id: 95269,
          name: 'Toilet-Bound Hanako-kun',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '地縛少年花子くん',
          overview:
            "The famous \"Seven Wonders\" that every school seems to have are a staple of Japanese urban legends. One of the most well-known of these tales is that of Hanako-san: the ghost of a young girl who haunts the school's bathrooms.\n\nKamome Academy has its own version of Hanako-san's legend. Rumors claim that if one successfully manages to summon Hanako-san, she will grant her summoner any wish. Lured by the gossip, many people have tried to call upon her, yet every attempt has failed. However, when Nene Yashiro, a girl hoping for romantic fortune, dares to summon Hanako-san, she discovers that the rumored \"girl\" is actually a boy!\n\nAfter a series of unfortunate events involving Nene's romantic desires, she is unwillingly entangled in the world of the supernatural, becoming Hanako-kun's assistant. Soon, she finds out about Hanako-kun's lesser-known duty: maintaining the fragile balance between mortals and apparitions.",
          popularity: 43.363,
          poster_path: '/qp2XSpNzopObSPkSAi7sujAsdh3.jpg',
          vote_average: 8.7,
          vote_count: 599,
        },
        {
          backdrop_path: '/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg',
          first_air_date: '2019-04-06',
          genre_ids: [16, 10765, 10759],
          id: 85937,
          name: 'Demon Slayer: Kimetsu no Yaiba',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '鬼滅の刃',
          overview:
            'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
          popularity: 110.745,
          poster_path: '/wrCVHdkBlBWdJUZPvnJWcBRuhSY.jpg',
          vote_average: 8.7,
          vote_count: 4297,
        },
        {
          backdrop_path: '/uAjMQlbPkVHmUahhCouANlHSDW2.jpg',
          first_air_date: '2019-01-11',
          genre_ids: [16, 9648, 10765, 10759, 18, 80],
          id: 83097,
          name: 'The Promised Neverland',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '約束のネバーランド',
          overview:
            'Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their "Mama," Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage — a rule they are expected to follow no matter what. However, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family... never to be heard from again.\n\nHowever, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.',
          popularity: 33.419,
          poster_path: '/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg',
          vote_average: 8.7,
          vote_count: 839,
        },
        {
          backdrop_path: '/2f8OLO6UYp78dIQMs0oi7ja15Bl.jpg',
          first_air_date: '2010-04-02',
          genre_ids: [16, 35, 18],
          id: 65648,
          name: 'Maid Sama!',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: '会長はメイド様！',
          overview:
            'Misaki Ayuzawa is the first female student council president at a once all-boys school turned co-ed. She rules the school with strict discipline demeanor. But she has a secret—she works at a maid cafe due to her families circumstances. One day the popular A-student and notorious heart breaker Takumi Usui finds out her secret and makes a deal with her to keep it hush from the school in exchange for spending some time with him.',
          popularity: 23.929,
          poster_path: '/igkn0M1bgMeATz59LShvVxZNdVd.jpg',
          vote_average: 8.7,
          vote_count: 475,
        },
        {
          backdrop_path: '/bhF63Jd90gRYyTHd4y5GCGA2vX6.jpg',
          first_air_date: '2010-09-06',
          genre_ids: [16, 35],
          id: 31132,
          name: 'Regular Show',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Regular Show',
          overview:
            'Two bored groundskeepers, Mordecai (a six-foot-tall blue jay) and Rigby (a hyperactive raccoon) are best friends who spend their days trying to entertain themselves by any means necessary, much to the displeasure of their boss. Their everyday pursuits often lead to things spiraling out of control and into the surreal.',
          popularity: 245.086,
          poster_path: '/mS5SLxMYcKfUxA0utBSR5MOAWWr.jpg',
          vote_average: 8.7,
          vote_count: 1534,
        },
        {
          backdrop_path: '/70YdbMELM4b8x8VXjlubymb2bQ0.jpg',
          first_air_date: '2017-03-19',
          genre_ids: [18, 10751],
          id: 70785,
          name: 'Anne with an E',
          origin_country: ['CA'],
          original_language: 'en',
          original_name: 'Anne with an E',
          overview:
            'A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.',
          popularity: 149.65,
          poster_path: '/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg',
          vote_average: 8.7,
          vote_count: 4000,
        },
        {
          backdrop_path: '/mmEJYkP5mpWsgsJPxLulcL6y4Ir.jpg',
          first_air_date: '2020-10-31',
          genre_ids: [16, 35, 10765],
          id: 95666,
          name: 'Helluva Boss',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Helluva Boss',
          overview:
            'Follow Blitzo, a classic demon Imp who sets out to run his own small assassin business with his weapons specialist Moxxie, his bruiser Millie, and his receptionist hellhound Loona. Together they attempt to survive each other while running a startup in Hell.',
          popularity: 23.777,
          poster_path: '/mEHUgujxM62HtOyqNgZFENMIqgb.jpg',
          vote_average: 8.7,
          vote_count: 434,
        },
        {
          backdrop_path: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
          first_air_date: '2021-03-25',
          genre_ids: [16, 10765, 10759, 18],
          id: 95557,
          name: 'Invincible',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Invincible',
          overview:
            'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
          popularity: 93.642,
          poster_path: '/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',
          vote_average: 8.7,
          vote_count: 3172,
        },
        {
          backdrop_path: '/dJ8yrSokdTMnhKJw06MllSfCegb.jpg',
          first_air_date: '2019-01-12',
          genre_ids: [16, 35, 18],
          id: 83121,
          name: 'Kaguya-sama: Love Is War',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'かぐや様は告らせたい～天才たちの恋愛頭脳戦～',
          overview:
            "Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy's student council as its president, working alongside the beautiful and wealthy vice president Kaguya Shinomiya. The two are often regarded as the perfect couple by students despite them not being in any sort of romantic relationship.",
          popularity: 69.547,
          poster_path: '/5khbC6AuNgnvnoDbjIMKCOhEtIc.jpg',
          vote_average: 8.7,
          vote_count: 544,
        },
        {
          backdrop_path: '/mBxsapX4DNhH1XkOlLp15He5sxL.jpg',
          first_air_date: '1999-10-20',
          genre_ids: [10759, 35, 16],
          id: 37854,
          name: 'One Piece',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'ワンピース',
          overview:
            'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates. Monkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way. Luffy will do anything to get the One Piece and become King of the Pirates!',
          popularity: 100.351,
          poster_path: '/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg',
          vote_average: 8.7,
          vote_count: 3225,
        },
      ],
      total_pages: 128,
      total_results: 2559,
      title: 'Series más valoradas',
    },
    {
      title: 'Series populares',
      page: 1,
      results: [
        {
          backdrop_path: '/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg',
          first_air_date: '2022-08-21',
          genre_ids: [18, 10759, 10765, 9648],
          id: 94997,
          name: 'House of the Dragon',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'House of the Dragon',
          overview:
            'The prequel series finds the Targaryen dynasty at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires—real and imagined—crumble from such heights. In the case of the Targaryens, their slow fall begins almost 193 years before the events of Game of Thrones, when King Viserys Targaryen breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
          popularity: 6455.182,
          poster_path: '/z2yahl2uefxDCl0nogcRBstwruJ.jpg',
          vote_average: 8.7,
          vote_count: 932,
        },
        {
          backdrop_path: '/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg',
          first_air_date: '2022-08-18',
          genre_ids: [35, 10765],
          id: 92783,
          name: 'She-Hulk: Attorney at Law',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'She-Hulk: Attorney at Law',
          overview:
            'Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.',
          popularity: 6259.555,
          poster_path: '/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg',
          vote_average: 7.3,
          vote_count: 605,
        },
        {
          backdrop_path: '/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg',
          first_air_date: '2022-09-01',
          genre_ids: [10765, 10759, 18],
          id: 84773,
          name: 'The Lord of the Rings: The Rings of Power',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'The Lord of the Rings: The Rings of Power',
          overview:
            'Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.',
          popularity: 6145.327,
          poster_path: '/suyNxglk17Cpk8rCM2kZgqKdftk.jpg',
          vote_average: 7.6,
          vote_count: 368,
        },
        {
          backdrop_path: '/uGy4DCmM33I7l86W7iCskNkvmLD.jpg',
          first_air_date: '2013-12-02',
          genre_ids: [16, 35, 10765, 10759],
          id: 60625,
          name: 'Rick and Morty',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Rick and Morty',
          overview:
            "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
          popularity: 1566.773,
          poster_path: '/sGVCWtLG37mLOhl11qQVrjKsDzx.jpg',
          vote_average: 8.7,
          vote_count: 6839,
        },
        {
          backdrop_path: '/jW61BMd1ZVWPXI7Ts4iC2BTx8Qj.jpg',
          first_air_date: '2022-04-11',
          genre_ids: [18],
          id: 196572,
          name: 'The Secret House',
          origin_country: ['KR'],
          original_language: 'ko',
          original_name: '비밀의 집',
          overview:
            'A story about quitting being a good boy and chasing evil to the end for the sake of the mother and sister who sacrificed for themselves.\n\nA revenge play in which a dirt spoon lawyer chasing the traces of his missing mother walks into the secret surrounding him to fight the world.',
          popularity: 1401.536,
          poster_path: '/wNN9hJDV45BF2PiJQQVwBCiqLIl.jpg',
          vote_average: 5.3,
          vote_count: 10,
        },
        {
          backdrop_path: '/eqhKMZTLcieAvoH6CBqknTTfNby.jpg',
          first_air_date: '2022-08-05',
          genre_ids: [10765, 18],
          id: 90802,
          name: 'The Sandman',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'The Sandman',
          overview:
            'After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.',
          popularity: 1381.783,
          poster_path: '/q54qEgagGOYCq5D1903eBVMNkbo.jpg',
          vote_average: 8.2,
          vote_count: 749,
        },
        {
          backdrop_path: '/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
          first_air_date: '2011-04-17',
          genre_ids: [10765, 18, 10759],
          id: 1399,
          name: 'Game of Thrones',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Game of Thrones',
          overview:
            "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
          popularity: 1272.693,
          poster_path: '/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
          vote_average: 8.4,
          vote_count: 18949,
        },
        {
          backdrop_path: '/kOkmTrD8kWLeTXcAEwctg6GwW7t.jpg',
          first_air_date: '2017-02-20',
          genre_ids: [10751, 35],
          id: 91759,
          name: 'Come Home Love: Lo and Behold',
          origin_country: ['HK'],
          original_language: 'cn',
          original_name: '愛．回家之開心速遞',
          overview:
            "Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
          popularity: 1192.788,
          poster_path: '/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg',
          vote_average: 4.7,
          vote_count: 9,
        },
        {
          backdrop_path: '/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg',
          first_air_date: '2022-08-22',
          genre_ids: [10766, 18],
          id: 204095,
          name: 'Mar do Sertão',
          origin_country: ['BR'],
          original_language: 'pt',
          original_name: 'Mar do Sertão',
          overview: '',
          popularity: 1187.109,
          poster_path: '/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg',
          vote_average: 5.3,
          vote_count: 3,
        },
        {
          backdrop_path: '/x0RRnWdYeczF4KXDqW8blda7SKS.jpg',
          first_air_date: '2022-03-28',
          genre_ids: [18, 10766],
          id: 158415,
          name: 'Pantanal',
          origin_country: ['BR'],
          original_language: 'pt',
          original_name: 'Pantanal',
          overview:
            'After the mysterious disappearance of his father, Joventino, the cowboy José Leôncio becomes a wealthy farm owner in Pantanal. Over twenty years have passed and, bitter-hearted because of his father vanishing and the escape of his wife to Rio de Janeiro with his baby, José Leôncio has the chance to make amends with the boy, now a young man raised in the big city with very different values and habits than his own.',
          popularity: 964.463,
          poster_path: '/i1HJ7Eol9BRX3XH73vJV6lkIXP0.jpg',
          vote_average: 5.7,
          vote_count: 47,
        },
        {
          backdrop_path: '/ry9SsBPOShH7eEL2dJc1coCBh8X.jpg',
          first_air_date: '2022-03-07',
          genre_ids: [35, 18],
          id: 157936,
          name: 'For You',
          origin_country: ['PT'],
          original_language: 'pt',
          original_name: 'Por Ti',
          overview:
            'In the parish of Rio Meandro, two villages are at war over the construction of a dam that will submerge one of them: either Aldeia Velha or Aldeia Nova.',
          popularity: 937.404,
          poster_path: '/7GmlOYoR2GNiBRFs47azHIcqncR.jpg',
          vote_average: 5.3,
          vote_count: 10,
        },
        {
          backdrop_path: '/cImIRobqw7AGr7c2s1vX5BgLy7v.jpg',
          first_air_date: '2022-08-11',
          genre_ids: [18],
          id: 108664,
          name: 'Five Days at Memorial',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Five Days at Memorial',
          overview:
            'Based on actual events from Hurricane Katrina. When the floodwaters rose, power failed, and heat soared, exhausted caregivers at a New Orleans hospital were forced to make profound, heart-wrenching decisions.',
          popularity: 935.515,
          poster_path: '/zGCfczI98fG6LljFlvIhoo0jtq9.jpg',
          vote_average: 7.8,
          vote_count: 16,
        },
        {
          backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
          first_air_date: '2016-07-15',
          genre_ids: [18, 10765, 9648],
          id: 66732,
          name: 'Stranger Things',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Stranger Things',
          overview:
            'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
          popularity: 912.926,
          poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
          vote_average: 8.6,
          vote_count: 13445,
        },
        {
          backdrop_path: '/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg',
          first_air_date: '2016-01-25',
          genre_ids: [80, 10765],
          id: 63174,
          name: 'Lucifer',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'Lucifer',
          overview:
            "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
          popularity: 843.756,
          poster_path: '/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
          vote_average: 8.5,
          vote_count: 12402,
        },
        {
          backdrop_path: '/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg',
          first_air_date: '2013-09-12',
          genre_ids: [18, 80],
          id: 60574,
          name: 'Peaky Blinders',
          origin_country: ['GB'],
          original_language: 'en',
          original_name: 'Peaky Blinders',
          overview:
            'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
          popularity: 842.807,
          poster_path: '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
          vote_average: 8.6,
          vote_count: 7313,
        },
        {
          backdrop_path: '/ic7YfRS52N3m4oalxoOIT665C33.jpg',
          first_air_date: '2020-07-08',
          genre_ids: [18, 35],
          id: 104877,
          name: 'Love Is In The Air',
          origin_country: ['TR'],
          original_language: 'tr',
          original_name: 'Sen Çal Kapımı',
          overview:
            "Eda, who ties all her hopes to her education, confronts Serkan Bolat, who cuts off her international education scholarship and leaves her with high school diploma. Serkan Bolat offers Eda to give her scholarship back if she pretends to be his fiance for two months. Although Eda rejects the offer of this man as she hates him, she has to accept it when the conditions change. While pretending to be engaged, Serkan and Eda begin to experience a passionate, challenging relationship that will make them forget all they know right. Because love is difficult. And that's why it's amazing.",
          popularity: 826.169,
          poster_path: '/bE71f9A3eztjcd5JT3MmHB8MbzA.jpg',
          vote_average: 8.2,
          vote_count: 2613,
        },
        {
          backdrop_path: '/wcbrJB42U6yQuwLC3icxJrjc52w.jpg',
          first_air_date: '2022-05-30',
          genre_ids: [35, 10765],
          id: 152296,
          name: 'Love in 40 Days',
          origin_country: ['PH'],
          original_language: 'tl',
          original_name: 'Love in 40 Days',
          overview:
            'After getting involved in a fatal car crash, a competitive career woman arrives in an uncanny purgatory. While settling her unfinished businesses as a lingering spirit, she meets and finds her soulmate in a rebellious scion with a third eye.',
          popularity: 810.045,
          poster_path: '/x7qeqSNB5wN93U2EvOniELSXuNz.jpg',
          vote_average: 3.9,
          vote_count: 5,
        },
        {
          backdrop_path: '/xlKKD1TXJvh0YYlVPqqQ3g3ZUjM.jpg',
          first_air_date: '2018-07-01',
          genre_ids: [16, 10759, 10765],
          id: 80020,
          name: 'Super Dragon Ball Heroes',
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'スーパードラゴンボールヒーローズ',
          overview:
            'Trunks returns from the future to train with Goku and Vegeta. However, it disappears without warning. Then the mysterious Fu bursts in, telling them that Trunks has been imprisoned in the Prison Planet, a mysterious complex in an unknown place in the universes. The group seeks the dragon balls to free Trunks, but an endless battle awaits them! Will Goku and the others rescue Trunks and escape the Prison Planet?',
          popularity: 800.079,
          poster_path: '/8jq6xv5c1WK7KAPOXCsodm8eUxp.jpg',
          vote_average: 7.6,
          vote_count: 2735,
        },
        {
          backdrop_path: '/68sanslplXryiJWzv0uMuXjJBmB.jpg',
          first_air_date: '2019-07-25',
          genre_ids: [10765, 10759],
          id: 76479,
          name: 'The Boys',
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'The Boys',
          overview:
            'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
          popularity: 797.082,
          poster_path: '/stTEycfG9928HYGEISBFaG1ngjM.jpg',
          vote_average: 8.5,
          vote_count: 7285,
        },
        {
          backdrop_path: '/7J5d7K4JBDZ4IDODNX3THLggtM5.jpg',
          first_air_date: '2005-03-27',
          genre_ids: [18],
          id: 1416,
          name: "Grey's Anatomy",
          origin_country: ['US'],
          original_language: 'en',
          original_name: "Grey's Anatomy",
          overview:
            'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
          popularity: 792.528,
          poster_path: '/zPIug5giU8oug6Xes5K1sTfQJxY.jpg',
          vote_average: 8.3,
          vote_count: 8360,
        },
      ],
      total_pages: 6815,
      total_results: 136286,
      title: 'Series populares',
    },
  ];

  return {
    props: {
      list,
    },
  };
}

export default Catalog;
